In [11]:
#Load the YAML configuration 
%load_ext autoreload
%autoreload 2
from eeg_toolkit import (
    load_config,
    extract_mean_band_power,
)
cfg = load_config('../../configs/eye_eeg_simul.yaml')
cfg_tfr = load_config('../../configs/tfr_analysis.yaml')
print("Setup OK")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Setup OK

In [3]:
#Here you are going to select the ROIs in the three dimension that you are interested to export
rois = {
    "frontal_mid":    ["Fz", "F3", "F4"],
    "central_mid":    ["Cz", "C3", "C4"],
    "posterior_mid":   ["Pz", "Oz"],
    "posterior_left":  ["P3", "P7", "O1"],
    "posterior_right": ["P4", "P8", "O2"],
}

freq_bands = {
    "theta": (4, 8),
    "alpha": (8, 13),
    "beta":  (13, 30),
}

time_windows = {
    "early":  (0.1, 0.3),
    "mid":    (0.3, 0.5),
    "late":   (0.5, 0.8),
}

In [7]:
#Here we are constructing the data frame that is going to store the values of all the data you wanted to extract to 
#later export it to a csv and run some statistical testings.
df = extract_mean_band_power(
    cfg, cfg_tfr, "cue", rois, freq_bands, time_windows,
    conditions=["spatial", "symbolic"]
)
df.head(10)

[find_subjects] excluded 8 subject(s): ['subj13', 'subj15', 'subj16', 'subj17', 'subj2', 'subj20', 'subj28', 'subj7']
Extracted 2700 rows: 30 subjects × 2 conditions × 5 ROIs × 3 bands × 3 time windows

,subject,condition,roi,channels,freq_band,fmin,fmax,time_window,tmin,tmax,mean_power
0,subj3,spatial,frontal_mid,"Fz, F3, F4",theta,4,8,early,0.1,0.3,0.090832
1,subj3,spatial,frontal_mid,"Fz, F3, F4",theta,4,8,mid,0.3,0.5,0.013796
2,subj3,spatial,frontal_mid,"Fz, F3, F4",theta,4,8,late,0.5,0.8,-0.070860
3,subj3,spatial,frontal_mid,"Fz, F3, F4",alpha,8,13,early,0.1,0.3,0.002950
4,subj3,spatial,frontal_mid,"Fz, F3, F4",alpha,8,13,mid,0.3,0.5,-0.145667
5,subj3,spatial,frontal_mid,"Fz, F3, F4",alpha,8,13,late,0.5,0.8,-0.304441
6,subj3,spatial,frontal_mid,"Fz, F3, F4",beta,13,30,early,0.1,0.3,-0.028272
7,subj3,spatial,frontal_mid,"Fz, F3, F4",beta,13,30,mid,0.3,0.5,-0.092859
8,subj3,spatial,frontal_mid,"Fz, F3, F4",beta,13,30,late,0.5,0.8,-0.097690
9,subj3,spatial,central_mid,"Cz, C3, C4",theta,4,8,early,0.1,0.3,0.057996

In [5]:
from eeg_toolkit.io import get_analysis_dir
out_dir = get_analysis_dir(cfg) / "group_results" / "tfr" / "stats"
out_dir.mkdir(parents=True, exist_ok=True)

out_path = out_dir / "mean_band_power_cue.csv"
df.to_csv(out_path, index=False)
print(f"Saved: {out_path}")

Saved: C:\Users\juapa\OneDrive\Documentos\Proyecto doctorado\Experimentos_proyecto_tesis\Experimentos Eye Tracker\analisis\analisis_eeg\group_results\tfr\stats\mean_band_power_cue.csv

In [8]:
#This is a way to do the standard comparison spatial vs symbolic in my design with all the possible variables that
# were selected on the previous code, this is just a way to do it in python, but with the csv it can be done in any statistical 
#software
from eeg_toolkit import run_tfr_paired_tests

stats_df = run_tfr_paired_tests(df, contrast=("spatial", "symbolic"))
stats_df

Paired tests: 45 comparisons, 0 significant after FDR

,roi,freq_band,fmin,fmax,time_window,tmin,tmax,n,mean_a,mean_b,mean_diff,cohens_d,t_stat,p_ttest,w_stat,p_wilcoxon,p_fdr,sig_fdr,contrast
0,central_mid,alpha,8,13,early,0.1,0.3,30,0.008721,0.006157,0.002564,0.046993,0.257393,0.798693,206.0,0.597808,0.954240,False,spatial_vs_symbolic
1,central_mid,alpha,8,13,late,0.5,0.8,30,-0.147528,-0.148546,0.001018,0.015785,0.086460,0.931695,228.0,0.935399,0.954240,False,spatial_vs_symbolic
2,central_mid,alpha,8,13,mid,0.3,0.5,30,-0.054540,-0.062187,0.007646,0.123372,0.675735,0.504562,185.0,0.338742,0.870281,False,spatial_vs_symbolic
3,frontal_mid,alpha,8,13,early,0.1,0.3,30,-0.028222,-0.042947,0.014725,0.220216,1.206172,0.237500,176.0,0.253436,0.822115,False,spatial_vs_symbolic
4,frontal_mid,alpha,8,13,late,0.5,0.8,30,-0.155903,-0.171779,0.015876,0.230414,1.262029,0.216994,170.0,0.205410,0.813729,False,spatial_vs_symbolic
5,frontal_mid,alpha,8,13,mid,0.3,0.5,30,-0.097324,-0.119878,0.022554,0.293209,1.605974,0.119115,156.0,0.119077,0.724268,False,spatial_vs_symbolic
6,posterior_left,alpha,8,13,early,0.1,0.3,30,-0.074771,-0.086310,0.011540,0.171061,0.936941,0.356527,182.0,0.308521,0.832743,False,spatial_vs_symbolic
7,posterior_left,alpha,8,13,late,0.5,0.8,30,-0.245114,-0.247047,0.001933,0.030378,0.166389,0.869006,223.0,0.855272,0.954240,False,spatial_vs_symbolic
8,posterior_left,alpha,8,13,mid,0.3,0.5,30,-0.176722,-0.185997,0.009275,0.124581,0.682357,0.500428,214.0,0.715133,0.870281,False,spatial_vs_symbolic
9,posterior_mid,alpha,8,13,early,0.1,0.3,30,-0.092993,-0.107643,0.014649,0.259122,1.419267,0.166481,163.0,0.157948,0.749165,False,spatial_vs_symbolic
10,posterior_mid,alpha,8,13,late,0.5,0.8,30,-0.279665,-0.282364,0.002699,0.037103,0.203222,0.840380,220.0,0.807830,0.954240,False,spatial_vs_symbolic
11,posterior_mid,alpha,8,13,mid,0.3,0.5,30,-0.196973,-0.215635,0.018662,0.279691,1.531930,0.136377,162.0,0.151887,0.724268,False,spatial_vs_symbolic
12,posterior_right,alpha,8,13,early,0.1,0.3,30,-0.130569,-0.149230,0.018661,0.273557,1.498335,0.144854,159.0,0.134735,0.724268,False,spatial_vs_symbolic
13,posterior_right,alpha,8,13,late,0.5,0.8,30,-0.316166,-0.331326,0.015160,0.174058,0.953356,0.348289,192.0,0.416130,0.832743,False,spatial_vs_symbolic
14,posterior_right,alpha,8,13,mid,0.3,0.5,30,-0.256611,-0.284009,0.027397,0.367831,2.014696,0.053292,152.0,0.100397,0.724268,False,spatial_vs_symbolic
15,central_mid,beta,13,30,early,0.1,0.3,30,0.008281,0.006705,0.001576,0.033029,0.180908,0.857699,230.0,0.967674,0.954240,False,spatial_vs_symbolic
16,central_mid,beta,13,30,late,0.5,0.8,30,-0.075995,-0.075155,-0.000840,-0.016304,-0.089298,0.929459,219.0,0.792159,0.954240,False,spatial_vs_symbolic
17,central_mid,beta,13,30,mid,0.3,0.5,30,-0.052498,-0.049269,-0.003229,-0.062762,-0.343762,0.733505,205.0,0.583757,0.954240,False,spatial_vs_symbolic
18,frontal_mid,beta,13,30,early,0.1,0.3,30,-0.005850,0.008984,-0.014834,-0.402043,-2.202082,0.035764,134.0,0.042652,0.724268,False,spatial_vs_symbolic
19,frontal_mid,beta,13,30,late,0.5,0.8,30,-0.055729,-0.047494,-0.008236,-0.176558,-0.967046,0.341517,174.0,0.236652,0.832743,False,spatial_vs_symbolic
20,frontal_mid,beta,13,30,mid,0.3,0.5,30,-0.046017,-0.034808,-0.011210,-0.281988,-1.544513,0.133308,154.0,0.109432,0.724268,False,spatial_vs_symbolic
21,posterior_left,beta,13,30,early,0.1,0.3,30,-0.033977,-0.026155,-0.007822,-0.182270,-0.998334,0.326375,210.0,0.655438,0.832743,False,spatial_vs_symbolic
22,posterior_left,beta,13,30,late,0.5,0.8,30,-0.092337,-0.085647,-0.006690,-0.170500,-0.933865,0.358084,200.0,0.515848,0.832743,False,spatial_vs_symbolic
23,posterior_left,beta,13,30,mid,0.3,0.5,30,-0.079232,-0.069049,-0.010183,-0.280037,-1.533826,0.135911,168.0,0.190930,0.724268,False,spatial_vs_symbolic
24,posterior_mid,beta,13,30,early,0.1,0.3,30,-0.034482,-0.019886,-0.014596,-0.348791,-1.910409,0.066014,147.0,0.080327,0.724268,False,spatial_vs_symbolic
25,posterior_mid,beta,13,30,late,0.5,0.8,30,-0.107263,-0.093580,-0.013683,-0.358899,-1.965772,0.058965,155.0,0.114177,0.724268,False,spatial_vs_symbolic
26,posterior_mid,beta,13,30,mid,0.3,0.5,30,-0.081391,-0.073746,-0.007645,-0.179580,-0.983602,0.333447,187.0,0.359878,0.832743,False,spatial_vs_symbolic
27,posterior_right,beta,13,30,early,0.1,0.3,30,-0.059198,-0.053038,-0.006160,-0.128123,-0.701760,0.488423,203.0,0.556113,0.870281,False,spatial_vs_symbolic
28,posterior_right,beta,13,30,late,0.5,0.8,30,-0.112880,-0.109288,-0.003592,-0.081417,-0.445940,0.658953,204.0,0.569858,0.954240,False,spatial_vs_symbolic
29,posterior_right,beta,13,30,mid,0.3,0.5,30,-0.102577,-0.106524,0.003947,0.104643,0.573152,0.570960,226.0,0.903226,0.870281,False,spatial_vs_symbolic
30,central_mid,theta,4,8,early,0.1,0.3,30,0.078878,0.077764,0.001115,0.024483,0.134096,0.894253,223.0,0.855272,0.954240,False,spatial_vs_symbolic
31,central_mid,theta,4,8,late,0.5,0.8,30,0.003947,0.003995,-0.000048,-0.001103,-0.006043,0.995219,221.0,0.823577,0.995219,False,spatial_vs_symbolic
32,central_mid,theta,4,8,mid,0.3,0.5,30,0.062270,0.052220,0.010050,0.238212,1.304739,0.202241,170.0,0.205410,0.813729,False,spatial_vs_symbolic
33,frontal_mid,theta,4,8,early,0.1,0.3,30,0.068557,0.067529,0.001028,0.015475,0.084760,0.933035,231.0,0.983834,0.954240,False,spatial_vs_symbolic
34,frontal_mid,theta,4,8,late,0.5,0.8,30,0.005940,0.008773,-0.002833,-0.037975,-0.207996,0.836686,232.0,1.000000,0.954240,False,spatial_vs_symbolic
35,frontal_mid,theta,4,8,mid,0.3,0.5,30,0.042983,0.053388,-0.010406,-0.153838,-0.842604,0.406346,204.0,0.569858,0.832743,False,spatial_vs_symbolic
36,posterior_left,theta,4,8,early,0.1,0.3,30,0.075603,0.066414,0.009189,0.153581,0.841200,0.407119,187.0,0.359878,0.832743,False,spatial_vs_symbolic
37,posterior_left,theta,4,8,late,0.5,0.8,30,-0.051709,-0.047410,-0.004299,-0.067244,-0.368312,0.715315,212.0,0.685047,0.954240,False,spatial_vs_symbolic
38,posterior_left,theta,4,8,mid,0.3,0.5,30,0.018898,0.022358,-0.003460,-0.052382,-0.286906,0.776224,219.0,0.792159,0.954240,False,spatial_vs_symbolic
39,posterior_mid,theta,4,8,early,0.1,0.3,30,0.062542,0.057347,0.005194,0.102131,0.559395,0.580188,186.0,0.349211,0.870281,False,spatial_vs_symbolic
40,posterior_mid,theta,4,8,late,0.5,0.8,30,-0.052140,-0.045473,-0.006667,-0.107292,-0.587664,0.561306,221.0,0.823577,0.870281,False,spatial_vs_symbolic
41,posterior_mid,theta,4,8,mid,0.3,0.5,30,0.032962,0.025286,0.007676,0.124281,0.680715,0.501451,175.0,0.244946,0.870281,False,spatial_vs_symbolic
42,posterior_right,theta,4,8,early,0.1,0.3,30,0.060765,0.050080,0.010685,0.154259,0.844912,0.405077,213.0,0.700033,0.832743,False,spatial_vs_symbolic
43,posterior_right,theta,4,8,late,0.5,0.8,30,-0.093079,-0.089175,-0.003904,-0.058304,-0.319343,0.751756,228.0,0.935399,0.954240,False,spatial_vs_symbolic
44,posterior_right,theta,4,8,mid,0.3,0.5,30,-0.015772,-0.023456,0.007685,0.103684,0.567903,0.574472,191.0,0.404495,0.870281,False,spatial_vs_symbolic

In [9]:
# Only theta at posterior ROIs, just to show how to filter the df and apply the same paired test. 
df_post_theta = df[
    (df["freq_band"] == "theta") &
    (df["roi"].isin(["posterior_mid", "posterior_left", "posterior_right"]))
]
run_tfr_paired_tests(df_post_theta, contrast=("spatial", "symbolic"))

Paired tests: 9 comparisons, 0 significant after FDR

,roi,freq_band,fmin,fmax,time_window,tmin,tmax,n,mean_a,mean_b,mean_diff,cohens_d,t_stat,p_ttest,w_stat,p_wilcoxon,p_fdr,sig_fdr,contrast
0,posterior_left,theta,4,8,early,0.1,0.3,30,0.075603,0.066414,0.009189,0.153581,0.841200,0.407119,187.0,0.359878,0.776224,False,spatial_vs_symbolic
1,posterior_left,theta,4,8,late,0.5,0.8,30,-0.051709,-0.047410,-0.004299,-0.067244,-0.368312,0.715315,212.0,0.685047,0.776224,False,spatial_vs_symbolic
2,posterior_left,theta,4,8,mid,0.3,0.5,30,0.018898,0.022358,-0.003460,-0.052382,-0.286906,0.776224,219.0,0.792159,0.776224,False,spatial_vs_symbolic
3,posterior_mid,theta,4,8,early,0.1,0.3,30,0.062542,0.057347,0.005194,0.102131,0.559395,0.580188,186.0,0.349211,0.776224,False,spatial_vs_symbolic
4,posterior_mid,theta,4,8,late,0.5,0.8,30,-0.052140,-0.045473,-0.006667,-0.107292,-0.587664,0.561306,221.0,0.823577,0.776224,False,spatial_vs_symbolic
5,posterior_mid,theta,4,8,mid,0.3,0.5,30,0.032962,0.025286,0.007676,0.124281,0.680715,0.501451,175.0,0.244946,0.776224,False,spatial_vs_symbolic
6,posterior_right,theta,4,8,early,0.1,0.3,30,0.060765,0.050080,0.010685,0.154259,0.844912,0.405077,213.0,0.700033,0.776224,False,spatial_vs_symbolic
7,posterior_right,theta,4,8,late,0.5,0.8,30,-0.093079,-0.089175,-0.003904,-0.058304,-0.319343,0.751756,228.0,0.935399,0.776224,False,spatial_vs_symbolic
8,posterior_right,theta,4,8,mid,0.3,0.5,30,-0.015772,-0.023456,0.007685,0.103684,0.567903,0.574472,191.0,0.404495,0.776224,False,spatial_vs_symbolic